frontend/models/Cart.php
<?php

namespace frontend\models;

use yii\bootstrap\Html;
use yii\db\ActiveRecord;

class Cart extends ActiveRecord
{
    public function addtoCart($product, $quantity = 1){

    if (isset($_SESSION['cart'][$product->id])) {
        $_SESSION['cart'][$product->id]['quantity'] += $quantity;
    }
    else {
        $_SESSION['cart'][$product->id] = [
            'SKU' => $product->SKU,
            'quantity' => $quantity,
            'title' => $product->title,
            'price' => $product->price,
            'img' => 'images/products/product1.jpg',
        ];

    }
        $_SESSION['cart.quantity'] = isset($_SESSION['cart.quantity']) ? $_SESSION['cart.quantity'] + $quantity : $quantity;
        $_SESSION['cart.sum'] = isset($_SESSION['cart.sum']) ? $_SESSION['cart.sum'] + $quantity * $product->price : $quantity * $product->price;
    }

    public function recalc($id){
        if(!isset($_SESSION['cart'][$id])) return false;

        $quantityMinus = $_SESSION['cart'][$id]['quantity'];
        $sumMinus = $_SESSION['cart'][$id]['quantity'] * $_SESSION['cart'][$id]['price'];

        $_SESSION['cart.quantity'] -=$quantityMinus;
        $_SESSION['cart.sum'] -= $sumMinus;
        unset( $_SESSION['cart'][$id]);

    }

}

frontend/controllers/CartController.php
<?php
/**
 * Created by PhpStorm.
 * User: betelgeyz
 * Date: 03.12.16
 * Time: 11:38
 */

namespace frontend\controllers;

use yii\base\Controller;
use common\models\Product;
use frontend\models\Cart;
use common\models\Order;
use common\models\OrderItems;
use Yii;

class CartController extends Controller
{
    public function actionAdd() {
        $id = Yii::$app->request->get('id');
        $quantity = (int)Yii::$app->request->get('quantity');
        $quantity = !$quantity ? 1 : $quantity;

        $product = Product::findOne($id);
        if (empty($product)) return false;
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->addToCart($product, $quantity);
        if (!Yii::$app->request->isAjax) {
            return Yii::$app->response->redirect(Yii::$app->request->referrer);
        }
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionClear() {
        $session = Yii::$app->session;
        $session->open();
        $session->remove('cart');
        $session->remove('cart.quantity');
        $session->remove('cart.sum');
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));


    }

    public function actionDelItem() {
        $id = Yii::$app->request->get('id');
        $session = Yii::$app->session;
        $session->open();
        $cart = new Cart();
        $cart->recalc($id);
        $this->layout = false;
        if (Yii::$app->request->isAjax) {
            return $this->render('cart-modal', compact('session'));
        } else {
            return Yii::$app->response->redirect(Yii::$app->request->referrer);
        }
    }

    public function actionShow() {
        $session = Yii::$app->session;
        $session->open();
        $this->layout = false;
        return $this->render('cart-modal', compact('session'));
    }

    public function actionView() {
        $session = Yii::$app->session;
        $session->open();
        $order = new Order();
        if( $order->load(Yii::$app->request->post()) && $order->validate() ) {
             if (!Yii::$app->user->isGuest && Yii::$app->user->identity->getId()) {
                $order->id_user = Yii::$app->user->identity->getId();
             } else {
                 $order->id_user = 4;
             };
            $order->quantity =$session['cart.quantity'];
            $order->totalPrice =$session['cart.sum'];
            if ($order->save()) {
                $this->saveOrderItems($session['cart'], $order->id);
                Yii::$app->session->setFlash('success', 'Ваш разаз принят');
                Yii::$app->mailer->compose('order/send', ['session' => $session])
                    ->setFrom([Yii::$app->params['adminEmail'] => 'Hot_shop'])
                    ->setTo($order->email)
                    ->setSubject('Ваш заказ принят')
                    ->send();
                $session->remove('cart');
                $session->remove('cart.quantity');
                $session->remove('cart.sum');
                return Yii::$app->response->refresh();
            } else {
                Yii::$app->session->setFlash('success', 'ошибка оформления заказа');
            }

        }
        return $this->render('view', compact('session', 'order'));
    }

    protected function saveOrderItems($items, $id_order) {
        foreach ($items as $id => $item) {
            $order_items = new OrderItems();
            $order_items->id_order = $id_order;
            $order_items->id_product = $id;
            $order_items->image = $item['img'];
            $order_items->SKU = $item['SKU'];
            $order_items->product_name = $item['title'];
            $order_items->price = $item['price'];
            $order_items->quantity_items = $item['quantity'];
            $order_items->total_price_items = $item['quantity'] * $item['price'];
            $order_items->save();
        }

    }

}

frontend/views/cart/cart-modal.php
<?php

use yii\helpers\Html;

?>
<?php if(!empty($session['cart'])): ?>
    <div class="table-responsive">
        <table class="table table-hover table-striped">
            <thead>
            <tr>
                <th>Фото</th>
                <th>SKU</th>
                <th>Наименование</th>
                <th>Кол-во</th>
                <th>Цена</th>
                <th>Сумма</th>
                <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
            </tr>
            </thead>
            <tbody>
            <?php foreach($session['cart'] as $id => $item):?>
                <tr>
                    <td><?= Html::img('@web/'.$item['img'], ["alt" => $item['title'] ]) ?></td>
                    <td><?= $item['SKU']?></td>
                    <td><?= $item['title']?></td>
                    <td><?= $item['quantity']?></td>
                    <td><?= $item['price']?></td>
                    <td><?= $item['quantity'] * $item['price']?></td>
                    <td><span data-id="<?= $id ?>" class="glyphicon glyphicon-remove text-danger del-item " aria-hidden="true"></span></td>
                </tr>
            <?php endforeach?>
            <tr>
                <td colspan="3">Итого: </td>
                <td colspan="2"><?= $session['cart.quantity']?></td>
                <td><?= $session['cart.sum']?></td>
                <td></td>

            </tr>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <h3>Корзина пуста</h3>
<?php endif;?>

frontend/views/cart/view.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;

?>

<div class="container" id="view_cart">
    <?php if( Yii::$app->session->hasFlash('success') ): ?>
        <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('success'); ?>
        </div>
    <?php endif;?>

    <?php if( Yii::$app->session->hasFlash('error') ): ?>
        <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <?php echo Yii::$app->session->getFlash('error'); ?>
        </div>
    <?php endif;?>

    <?php if(!empty($session['cart'])): ?>
        <div class="table-responsive">
            <table class="table table-hover table-striped">
                <thead>
                <tr>
                    <th>Фото</th>
                    <th>Наименование</th>
                    <th>SKU</th>
                    <th>Кол-во</th>
                    <th>Цена</th>
                    <th><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></th>
                </tr>
                </thead>
                <tbody>
                <?php foreach($session['cart'] as $id => $item):?>
                    <tr>
                        <td><?= Html::img('@web/'.$item['img'])?></td>
                        <td><?= Html::a($item['title'], ['product/view', 'id' => $id]) ?></td>
                        <td><?= $item['SKU']?></td>
                        <td><?= $item['quantity']?></td>
                        <td><?= $item['price']?></td>
                        <td><?= Html::a('<span data-id="<?= $id ?>" class="glyphicon glyphicon-remove text-danger del-item " aria-hidden="true"></span>', ['cart/del-item', 'id' => $id]) ?></td>
                    </tr>
                <?php endforeach?>
                <tr>
                    <td colspan="3">Итого: </td>
                    <td><?= $session['cart.quantity']?></td>
                    <td><?= $session['cart.sum']?></td>
                    <td></td>

                </tr>
                </tbody>
            </table>
            <hr/>

            <?php $form = ActiveForm::begin(['id' => 'orderAddress']) ?>
                <?= $form->field($order, 'username') ?>
                <?= $form->field($order, 'email') ?>
                <?= $form->field($order, 'phone') ?>
                <?= $form->field($order, 'address') ?>
                <?= Html::submitButton('order', ['class' => 'btn btn-success']) ?>
            <?php ActiveForm::end() ?>
        </div>
    <?php else: ?>
        <h3>Корзина пуста</h3>
    <?php endif;?>

</div>